/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as InstrumentsRouteImport } from './routes/instruments'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EnrollRouteImport } from './routes/enroll'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StudioTestimonialsRouteImport } from './routes/studio.testimonials'
import { Route as StudioStudentsRouteImport } from './routes/studio.students'
import { Route as StudioPackagesRouteImport } from './routes/studio.packages'
import { Route as StudioMessagesRouteImport } from './routes/studio.messages'
import { Route as StudioGalleryRouteImport } from './routes/studio.gallery'
import { Route as StudioBlogRouteImport } from './routes/studio.blog'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrumentsRoute = InstrumentsRouteImport.update({
  id: '/instruments',
  path: '/instruments',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollRoute = EnrollRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioTestimonialsRoute = StudioTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => StudioRoute,
} as any)
const StudioStudentsRoute = StudioStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => StudioRoute,
} as any)
const StudioPackagesRoute = StudioPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => StudioRoute,
} as any)
const StudioMessagesRoute = StudioMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => StudioRoute,
} as any)
const StudioGalleryRoute = StudioGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => StudioRoute,
} as any)
const StudioBlogRoute = StudioBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => StudioRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/enroll': typeof EnrollRoute
  '/gallery': typeof GalleryRoute
  '/instruments': typeof InstrumentsRoute
  '/programs': typeof ProgramsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRouteWithChildren
  '/testimonials': typeof TestimonialsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/studio/blog': typeof StudioBlogRoute
  '/studio/gallery': typeof StudioGalleryRoute
  '/studio/messages': typeof StudioMessagesRoute
  '/studio/packages': typeof StudioPackagesRoute
  '/studio/students': typeof StudioStudentsRoute
  '/studio/testimonials': typeof StudioTestimonialsRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/enroll': typeof EnrollRoute
  '/gallery': typeof GalleryRoute
  '/instruments': typeof InstrumentsRoute
  '/programs': typeof ProgramsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/studio/blog': typeof StudioBlogRoute
  '/studio/gallery': typeof StudioGalleryRoute
  '/studio/messages': typeof StudioMessagesRoute
  '/studio/packages': typeof StudioPackagesRoute
  '/studio/students': typeof StudioStudentsRoute
  '/studio/testimonials': typeof StudioTestimonialsRoute
  '/studio': typeof StudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/enroll': typeof EnrollRoute
  '/gallery': typeof GalleryRoute
  '/instruments': typeof InstrumentsRoute
  '/programs': typeof ProgramsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRouteWithChildren
  '/testimonials': typeof TestimonialsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/studio/blog': typeof StudioBlogRoute
  '/studio/gallery': typeof StudioGalleryRoute
  '/studio/messages': typeof StudioMessagesRoute
  '/studio/packages': typeof StudioPackagesRoute
  '/studio/students': typeof StudioStudentsRoute
  '/studio/testimonials': typeof StudioTestimonialsRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/enroll'
    | '/gallery'
    | '/instruments'
    | '/programs'
    | '/sitemap.xml'
    | '/studio'
    | '/testimonials'
    | '/blog/$slug'
    | '/studio/blog'
    | '/studio/gallery'
    | '/studio/messages'
    | '/studio/packages'
    | '/studio/students'
    | '/studio/testimonials'
    | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/enroll'
    | '/gallery'
    | '/instruments'
    | '/programs'
    | '/sitemap.xml'
    | '/testimonials'
    | '/blog/$slug'
    | '/studio/blog'
    | '/studio/gallery'
    | '/studio/messages'
    | '/studio/packages'
    | '/studio/students'
    | '/studio/testimonials'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/enroll'
    | '/gallery'
    | '/instruments'
    | '/programs'
    | '/sitemap.xml'
    | '/studio'
    | '/testimonials'
    | '/blog/$slug'
    | '/studio/blog'
    | '/studio/gallery'
    | '/studio/messages'
    | '/studio/packages'
    | '/studio/students'
    | '/studio/testimonials'
    | '/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  EnrollRoute: typeof EnrollRoute
  GalleryRoute: typeof GalleryRoute
  InstrumentsRoute: typeof InstrumentsRoute
  ProgramsRoute: typeof ProgramsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudioRoute: typeof StudioRouteWithChildren
  TestimonialsRoute: typeof TestimonialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instruments': {
      id: '/instruments'
      path: '/instruments'
      fullPath: '/instruments'
      preLoaderRoute: typeof InstrumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enroll': {
      id: '/enroll'
      path: '/enroll'
      fullPath: '/enroll'
      preLoaderRoute: typeof EnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/testimonials': {
      id: '/studio/testimonials'
      path: '/testimonials'
      fullPath: '/studio/testimonials'
      preLoaderRoute: typeof StudioTestimonialsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/students': {
      id: '/studio/students'
      path: '/students'
      fullPath: '/studio/students'
      preLoaderRoute: typeof StudioStudentsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/packages': {
      id: '/studio/packages'
      path: '/packages'
      fullPath: '/studio/packages'
      preLoaderRoute: typeof StudioPackagesRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/messages': {
      id: '/studio/messages'
      path: '/messages'
      fullPath: '/studio/messages'
      preLoaderRoute: typeof StudioMessagesRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/gallery': {
      id: '/studio/gallery'
      path: '/gallery'
      fullPath: '/studio/gallery'
      preLoaderRoute: typeof StudioGalleryRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/blog': {
      id: '/studio/blog'
      path: '/blog'
      fullPath: '/studio/blog'
      preLoaderRoute: typeof StudioBlogRouteImport
      parentRoute: typeof StudioRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface StudioRouteChildren {
  StudioBlogRoute: typeof StudioBlogRoute
  StudioGalleryRoute: typeof StudioGalleryRoute
  StudioMessagesRoute: typeof StudioMessagesRoute
  StudioPackagesRoute: typeof StudioPackagesRoute
  StudioStudentsRoute: typeof StudioStudentsRoute
  StudioTestimonialsRoute: typeof StudioTestimonialsRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioBlogRoute: StudioBlogRoute,
  StudioGalleryRoute: StudioGalleryRoute,
  StudioMessagesRoute: StudioMessagesRoute,
  StudioPackagesRoute: StudioPackagesRoute,
  StudioStudentsRoute: StudioStudentsRoute,
  StudioTestimonialsRoute: StudioTestimonialsRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  EnrollRoute: EnrollRoute,
  GalleryRoute: GalleryRoute,
  InstrumentsRoute: InstrumentsRoute,
  ProgramsRoute: ProgramsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudioRoute: StudioRouteWithChildren,
  TestimonialsRoute: TestimonialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
